### ISSUE TITLE
[OpenCV] Cannot properly link OpenCV in simple project

### ISSUE THREAD

**Issue by omaralvarez** [conan-community/community#248]
### Description of Problem, Request, or Question

In the current OpenCV package when I try to use it outside of `conan create` I am not able to link to any function.

### Package Details
* Package Name/Version: **opencv/4.1.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-7.4**
* Conan version: **conan 1.17.2**
* Python version: **python 3.6.8**

### Steps to reproduce

_CMakeLists.txt_

```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.7.2)
PROJECT(repro)

SET(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

INCLUDE(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
CONAN_BASIC_SETUP()

ADD_EXECUTABLE(repro main.cpp)
TARGET_LINK_LIBRARIES(repro ${CONAN_LIBS})
```
_conanfile.txt_

```ini
[requires]
opencv/4.1.0@conan/stable

[generators]
cmake

[options]
opencv:shared=True
opencv:contrib=True
```

_main.cpp_

```cpp

#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>

using namespace cv;

int main(int argc, char *argv[]) 
{
    Mat repro = imread("IMG_0010_4.tif");
    return 0;
}
```

### Build logs

``` 
Scanning dependencies of target repro
[ 50%] Building CXX object CMakeFiles/repro.dir/src/main.cpp.o
[100%] Linking CXX executable bin/repro
CMakeFiles/repro.dir/src/main.cpp.o: In function `main':
main.cpp:(.text+0x6b): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
```

**Comment by uilianries** [comment]
Hi @omaralvarez !

Your system (CMake) is linking your project to libstdc++11, but your Conan settings is using libstdc++. The OpenCV that you have installed was linked to libstdc++ which is not compatible.

To update this configuration, run:

    conan profile update settings.compiler.libcxx=libstdc++11 default

This update says to Conan prefer libstdc++11 instead of libstdc++ (defaulted). You will need to install all packages again, because this property generates a different package.

There is more information about Conan and GCC ABI here: 
https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html

Regards.

**Comment by omaralvarez** [comment]
Thanks a lot! You were right, now everything works properly.
