### ISSUE TITLE
[OpenCV] Build fails if freetype is enabled

### ISSUE THREAD

**Issue by dab0bby** [conan-community/community#272]
### Description of Problem, Request, or Question
When building OpenCV with `contrib`, `nonfree` and `freetype` enabled the build fails due to linking errors in `freetype`.

When disabling `freetype` option the build process works.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1@conan/stable**
* Operating System: **Windows**
* Operation System Version: **Windows10**
* Compiler+version: **Visual Studio 2019**
* Conan version: **conan 1.18.1**
* Python version: **python 3.7.4**

### conanfile.txt:
```
[requires]
opencv/4.1.1@conan/stable
zlib/1.2.11@conan/stable

[options]
opencv:shared=True
opencv:freetype=True
opencv:openexr=False
opencv:contrib=True
opencv:nonfree=True

[generators]
cmake

[imports]
bin, *.dll -> ./bin # Copies all dll files from packages bin folder to my "bin" folder
lib, *.dylib* -> ./bin # Copies all dylib files from packages lib folder to my "bin" folder

```

### Build logs (Include if Available)
```
freetype.obj : error LNK2019: unresolved external symbol FT_Init_FreeType referenced in function "public: __cdecl cv::freetype::FreeType2Impl::FreeType2Impl(void)" (??0FreeType2Impl@freetype@cv@@QEAA@XZ) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Done_FreeType referenced in function "public: virtual __cdecl cv::freetype::FreeType2Impl::~FreeType2Impl(void)" (??1FreeType2Impl@freetype@cv@@UEAA@XZ) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
  opencv_fuzzy.vcxproj -> C:\.conan\004636\1\build_subfolder\bin\opencv_fuzzy411d.dll
freetype.obj : error LNK2019: unresolved external symbol FT_New_Face referenced in function "public: virtual void __cdecl cv::freetype::FreeType2Impl::loadFontData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)" (?loadFontData@FreeType2Impl@freetype@cv@@UEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
  opencv_plot.vcxproj -> C:\.conan\004636\1\build_subfolder\bin\opencv_plot411d.dll
freetype.obj : error LNK2019: unresolved external symbol FT_Done_Face referenced in function "public: virtual __cdecl cv::freetype::FreeType2Impl::~FreeType2Impl(void)" (??1FreeType2Impl@freetype@cv@@UEAA@XZ) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Set_Pixel_Sizes referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Load_Glyph referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Render_Glyph referenced in function "private: void __cdecl cv::freetype::FreeType2Impl::putTextBitmapBlend(class cv::debug_build_guard::_InputOutputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::Point_<int>,int,class cv::Scalar_<double>,int,int,bool)" (?putTextBitmapBlend@FreeType2Impl@freetype@cv@@AEAAXAEBV_InputOutputArray@debug_build_guard@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Point_@H@3@HV?$Scalar_@N@3@HH_N@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
  opencv_hfs.vcxproj -> C:\.conan\004636\1\build_subfolder\bin\opencv_hfs411d.dll
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Decompose referenced in function "private: void __cdecl cv::freetype::FreeType2Impl::putTextOutline(class cv::debug_build_guard::_InputOutputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::Point_<int>,int,class cv::Scalar_<double>,int,int,bool)" (?putTextOutline@FreeType2Impl@freetype@cv@@AEAAXAEBV_InputOutputArray@debug_build_guard@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Point_@H@3@HV?$Scalar_@N@3@HH_N@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Translate referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Transform referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Get_BBox referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_font_destroy referenced in function "public: virtual __cdecl cv::freetype::FreeType2Impl::~FreeType2Impl(void)" (??1FreeType2Impl@freetype@cv@@UEAA@XZ) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_create referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_destroy referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_guess_segment_properties referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_add_utf8 referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_get_glyph_infos referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_shape referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_ft_font_create referenced in function "public: virtual void __cdecl cv::freetype::FreeType2Impl::loadFontData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)" (?loadFontData@FreeType2Impl@freetype@cv@@UEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
C:\.conan\004636\1\build_subfolder\bin\opencv_freetype411d.dll : fatal error LNK1120: 19 unresolved externals [C:\.conan\004636\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
```

**Comment by dab0bby** [comment]
Current workaround:

Disable freetype in `conanfile.txt`:
```
opencv:freetype=False
```

**Comment by StefanoLusardi** [comment]
Same setup, same issue. The workaround is working.

For further investigation when invoking:
`conan install opencv/4.1.1@conan/stable --options opencv:contrib=True --build missing`
gives me:
`gettext/0.20.1@bincrafters/stable: Not found in local cache, looking in remotes...
gettext/0.20.1@bincrafters/stable: Trying with 'conan-center'...
ERROR: Failed requirement 'gettext/0.20.1@bincrafters/stable' from 'glib/2.58.3@bincrafters/stable'
ERROR: Unable to find 'gettext/0.20.1@bincrafters/stable' in remotes`

**Comment by dab0bby** [comment]
@StefanoLusardi have you added `https://api.bintray.com/conan/bincrafters/public-conan` to your remotes?

**Comment by SSE4** [comment]
mostly these errors are because requirements added non-transitively, I'll try to find if there is generic solution

**Comment by StefanoLusardi** [comment]
Yes, adding the remote allowed me to build the contrib, but it fails with opencv:freetype=True

**Comment by SSE4** [comment]
was fixed by https://github.com/conan-community/conan-opencv/pull/50

**Comment by nikhiljain217** [comment]
I am trying to build opencv on Windows 10, with options contrib=True and Freetype=True.

The build is failing with the same error 

Build logs: 
ffreetype.obj : error LNK2019: unresolved external symbol FT_Init_FreeType referenced in function "public: __cdecl cv::freetype::FreeType2Impl::FreeType2Impl(void)" (??0FreeType2Impl@freetype@cv@@QEAA@XZ) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Done_FreeType referenced in function "public: virtual __cdecl cv::freetype::FreeType2Impl::~FreeType2Impl(void)" (??1FreeType2Impl@freetype@cv@@UEAA@XZ) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_New_Face referenced in function "public: virtual void __cdecl cv::freetype::FreeType2Impl::loadFontData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)" (?loadFontData@FreeType2Impl@freetype@cv@@UEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Done_Face referenced in function "public: virtual __cdecl cv::freetype::FreeType2Impl::~FreeType2Impl(void)" (??1FreeType2Impl@freetype@cv@@UEAA@XZ) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Set_Pixel_Sizes referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Load_Glyph referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Render_Glyph referenced in function "private: void __cdeclcv::freetype::FreeType2Impl::putTextBitmapBlend(class cv::_InputOutputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::Point_<int>,int,class cv::Scalar_<double>,int,int,bool)" (?putTextBitmapBlend@FreeType2Impl@freetype@cv@@AEAAXAEBV_InputOutputArray@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Point_@H@3@HV?$Scalar_@N@3@HH_N@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Decompose referenced in function "private: void __cdecl cv::freetype::FreeType2Impl::putTextOutline(class cv::_InputOutputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::Point_<int>,int,class cv::Scalar_<double>,int,int,bool)" (?putTextOutline@FreeType2Impl@freetype@cv@@AEAAXAEBV_InputOutputArray@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Point_@H@3@HV?$Scalar_@N@3@HH_N@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Translate referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Transform referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol FT_Outline_Get_BBox referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_font_destroy referenced in function "public: virtual __cdecl cv::freetype::FreeType2Impl::~FreeType2Impl(void)" (??1FreeType2Impl@freetype@cv@@UEAA@XZ) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_create referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_destroy referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_guess_segment_properties referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,structstd::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_add_utf8 referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_buffer_get_glyph_infos referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_shape referenced in function "public: virtual class cv::Size_<int> __cdecl cv::freetype::FreeType2Impl::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,int,int *)" (?getTextSize@FreeType2Impl@freetype@cv@@UEAA?AV?$Size_@H@3@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPEAH@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
freetype.obj : error LNK2019: unresolved external symbol hb_ft_font_create referenced in function "public: virtual void __cdecl cv::freetype::FreeType2Impl::loadFontData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int)" (?loadFontData@FreeType2Impl@freetype@cv@@UEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]
C:\.conan\6c99f3\1\build_subfolder\bin\opencv_freetype430.dll : fatal error LNK1120: 19 unresolved externals [C:\.conan\6c99f3\1\build_subfolder\source_subfolder\modules\freetype\opencv_freetype.vcxproj]

I see the fix for this issue was to change the freeType version to 2.10.1. And my opencv conan file does have the fix. But build still fails. 

Can you please check this.
