### ISSUE TITLE
libalsa build on travis

### ISSUE THREAD

**Issue by madebr** [conan-community/community#3]
### Description of Problem, Request, or Question

Using libalsa on travis, as a dependency of a dependency, fails while compiling libalsa.

### Package Details (Include if Applicable)
* Package Name/Version: **libalsa/1.1.5**
* Operating System: **Linux** (Travis, unknown)
* Compiler+version: **gcc-4.8**

### Steps to reproduce (Include if Applicable)
1. Create a project that needs *libalsa* (e.g. bincrafter's openal)
2. Create a `build` folder and run `conan install --build=missing` in it

==>
* `libalsa` is apparently missing on travis and needs a rebuild
* compilation fails

Example project:
https://github.com/madebr/issues/tree/master/conan_openal_1
Travis output:
https://travis-ci.org/madebr/issues/builds/347213498

**Comment by lasote** [comment]
Looks like a problem of libalsa building against python3, do you need python support? We could try to add an option to disable the python support.

**Comment by madebr** [comment]
No, I just ran into this problem while trying to use conan for CI for an OSS project: OpenRW.

**Comment by lasote** [comment]
Ok, let's wait for this to end: https://travis-ci.org/conan-community/conan-libalsa/builds/347301919

- And then, in the OpenRW package recipe you could try to specify in your conanfile.py default options:

`default_options = "libalsa:disable_python=True"``

Please, let me know the result. You will need the `--build missing` because we are generating packages from >4.9

**Comment by madebr** [comment]
- Adding `libalsa:disable_python=True` to the `[options]` section of a `conanfile.txt` works: https://travis-ci.org/madebr/issues/builds/347312302
- Adding `'libalsa:disable_python=True'` to my `default_options` works (I need to upgrade gcc):
https://travis-ci.org/madebr/openrw/jobs/347342137
- Adding the snippet below to `configure(self)` of a `conanfile.py` does NOT work: https://travis-ci.org/madebr/openrw/builds/347313615 (Why is that? Can I include this somewhere in a function?)
```python
if 'libalsa' in self.options:
    self.options['libalsa'].disable_python = True
```

**Comment by lasote** [comment]
> I've installed gcc 6 :
Be careful, even installing gcc 6, your standard C/C++ library won't be updated, the typical problem you will have is to reuse those binaries in a modern distribution with gcc6, the linker can fail because of missing symbols. I recommend you to use Docker in CI.

> and libalsa does still need to rebuild.
Yes, I'm not building binaries for the non-default options, so you will always need to build from sources.

> Adding the snippet below to configure(self) of a conanfile.py does NOT work

I don't know, verify that it is entering in the "if", the options object are complex objects, maybe the "in" operator is not programmed correctly.
